### ISSUE TITLE
User Profile UI update

### ISSUE THREAD

**Issue by ralsuwaidi** [Coders-HQ/CodersHQ#121]
🏆 Task Description: Design a user interface system for users to display their information
👨‍🚀 Skills Needed: CSS, HTML

## **📝 Submission Requirements**

- Design a user system UI using either design tools like figma or HTML, CSS
- The user system must display the users information in an intuitive manner and allow for further details (i.e show some projects and have a button that shows all)
- Can use stock data for initial designs

## **💭 Resources & Inspiration**

- Have a look at dribbble, they have cool designs

[[Haystack: Group Details](https://dribbble.com/shots/15813990-Haystack-Group-Details)](https://dribbble.com/shots/15813990-Haystack-Group-Details)

![https://cdn.dribbble.com/users/1774675/screenshots/15813990/media/7b5821380a3c329381f6672c96b21bf9.png](https://cdn.dribbble.com/users/1774675/screenshots/15813990/media/7b5821380a3c329381f6672c96b21bf9.png)

**Comment by ramasbeinaty** [comment]
Profile design has been done by obito and shafariz
