### ISSUE TITLE
Adding User Settings in Database

### ISSUE THREAD

**Issue by gitanimous** [Coders-HQ/CodersHQ#17]
### It would be better if the data was passed to the root html file in `codershq/templates/base.html`

- themePreference (can be text/varchar): default value would be _**light**_ and _**dark**_ would be an option
- languagePreference (also text/varchar): default value would be _**en**_ and _**ar**_ would be an option

**Comment by ralsuwaidi** [comment]
where does the user details need to be fed into?

**Comment by gitanimous** [comment]
> where does the user details need to be fed into? @gitanimous
> Only to base.html?

yes

**Comment by ralsuwaidi** [comment]
#18 should be fixed here. Test it and merge if you think its working as intended.

**Comment by ralsuwaidi** [comment]
code refactor
