### ISSUE TITLE
Bug: Github URLs with https:// are invalid profiles

### ISSUE THREAD

**Issue by gitanimous** [Coders-HQ/CodersHQ#20]
##
This works:
![chrome_rSOfBlR64b](https://user-images.githubusercontent.com/34681035/110674208-1ab06e80-81eb-11eb-94f6-04e8486dfca2.png)

##
This does not work:
![chrome_OWpSzJmc4T](https://user-images.githubusercontent.com/34681035/110674225-20a64f80-81eb-11eb-8320-035f4588c001.png)

**Comment by ralsuwaidi** [comment]
I'll have a look at the regex when I come back

**Comment by ralsuwaidi** [comment]
issue not applicable due to login changes
